# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151005212135 on 2015-10-05 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('hashed_password', models.CharField(max_length=64)),
                ('station', models.CharField(max_length=128)),
                ('overall_rating', models.IntegerField()),
                ('tags', models.CharField(max_length=512)),
                ('next_show', models.DateField()),
            ],
        ),
    ]
